import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'p-3',
    'p-0.5',
    'px-1',
    'py-0.5',
    'px-8',
    'px-4',
    'py-4',
    'pb-1',
    'py-4',
    'top-4',
    'right-4',
    'z-50',
    'z-10',
    'w-16',
    'h-20',
    'w-4',
    'h-4',
    'w-6',
    'h-6',
    'w-8',
    'h-8',
    'w-full',
    'h-full',
    'h-12',
    'max-h-48',
    'min-h-screen',
    'text-xs',
    'text-sm',
    'text-lg',
    'text-center',
    'font-bold',
    'font-mono',
    'tracking-wide',
    'tracking-wider',
    'border',
    'border-2',
    'border-b',
    'border-dashed',
    'border-gray-600',
    'border-gray-500',
    'border-green-400',
    'bg-gray-800',
    'bg-gray-900',
    'bg-gray-700',
    'bg-red-600',
    'bg-red-700',
    'text-white',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-green-400',
    'opacity-0',
    'opacity-50',
    'group-hover:opacity-100',
    'hover:bg-red-700',
    'hover:border-gray-500',
    'transition-all',
    'transition-opacity',
    'duration-200',
    'cursor-pointer',
    'pointer-events-none',
    'overflow-hidden',
    'overflow-y-auto',
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'justify-end',
    'flex-shrink-0',
    'grid',
    'grid-cols-8',
    'gap-1',
    'relative',
    'absolute',
    'fixed',
    'hidden',
    'truncate',
    'object-cover',
    'shadow-lg',
    'space-y-2',
    'mb-1',
    'mb-2',
    'mb-0.5',
    'mt-1',
    'mt-3',
    'mx-auto',
    'container',
    'max-w-lg'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config 